In [62]:
import numpy as np
from numpy.random import default_rng

In [29]:
# Creating an array
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

sales_array = np.array(sales)

In [30]:
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [31]:
# What do each of the array properties return?
print(f'ndim: {sales_array.ndim}')
print(f'size: {sales_array.size}') # 
print(f'shape: {sales_array.shape}') # what is the size for each dimension
print(f'dtype: {sales_array.dtype}')

ndim: 1
size: 10
shape: (10,)
dtype: int64


In [32]:
sales_two = [[0, 5, 155, 0, 518] , [0, 1827, 616, 317, 325]]
sales_two_array = np.array(sales_two)
sales_two_array



array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [33]:
print(f'ndim: {sales_two_array.ndim}')
print(f'size: {sales_two_array.size}') # 
print(f'shape: {sales_two_array.shape}') # what is the size for each dimension
print(f'dtype: {sales_two_array.dtype}')

ndim: 2
size: 10
shape: (2, 5)
dtype: int64


In [34]:
array = np.array(range(5))

In [35]:
array

array([0, 1, 2, 3, 4])

In [36]:
array_2d = np.array([range(5), range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [37]:
array_2d + 1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [38]:
print(f'ndim: {array_2d.ndim}')
print(f'size: {array_2d.size}') # 
print(f'shape: {array_2d.shape}') # what is the size for each dimension
print(f'dtype: {array_2d.dtype}')

ndim: 2
size: 10
shape: (2, 5)
dtype: int64


In [ ]:
# To transpose an array
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [43]:
# Convert a list into a numpy array
my_list = [x * 10 for x in range(1, 11)]

my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [44]:
print(f'ndim: {my_array.ndim}')
print(f'size: {my_array.size}') # 
print(f'shape: {my_array.shape}') # what is the size for each dimension
print(f'dtype: {my_array.dtype}')

ndim: 1
size: 10
shape: (10,)
dtype: int64


### Array Creation

In [ ]:
print(f'ones array {np.ones(4,)}')
print(f'zeros array {np.zeros((2, 5), dtype = int)}')
print(f'a range array {np.arange(10)}') # Note the start at 0
print(f'spaced array {np.linspace(0, 100, 5)}') # Stop point is inclusive
print(f'transposed array {np.arange(1, 9, 2).reshape(2, 2)}') # chaining with a reshape

ones array [1. 1. 1. 1.]
zeros array [[0 0 0 0 0]
 [0 0 0 0 0]]
a range array [0 1 2 3 4 5 6 7 8 9]
spaced array [  0.  25.  50.  75. 100.]
transposed array [[1 3]
 [5 7]]


In [52]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

In [54]:
np.identity(10, 'int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [60]:
np.linspace(0, 100, 11)


array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Random Numbers

In [ ]:
rng = default_rng(12345) # Sets the seed
print(f'{rng}')

Generator(PCG64)


In [67]:
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [ ]:
# Specify a mean and std dev
rng = default_rng(12345) #Sets the seed
mean, stddev = 5, 1
random_normal = rng.normal(mean, stddev, size = 10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [69]:
rng = np.random.default_rng(616)
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [70]:
rng.integers(0, 10, 100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5])

In [ ]:
rng.normal(50, 5, 10) # sample from a distribution with mean of 50, stddev of 5, 10 numbers

array([53.53115044, 46.35468178, 46.1580894 , 52.89177118, 45.90693639,
       44.51748741, 57.41467712, 51.82624671, 53.9032125 , 53.21454641])

### Exercise

In [ ]:
# Create an array and reshape it into a 5 x 2 array
np.linspace(10, 100, 10).reshape(5, 2)
# np.arange(10, 101, 10).reshape(5, 2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [90]:
# Create a random array of numbers between zero and 1 in a 3 x 3 shape
rng = default_rng(2022)
random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [89]:
np.arange(1, 11)*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Array Slicing